from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class Actions:
    def get_actions_async(self, trigger_id: str | None = None, action_name: str | None = None, deployed: bool | None = None, installed: bool = False, page: int | None = None, per_page: int | None = None) -> Any: ...
    def create_action_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def update_action_async(self, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_action_async(self, id: str) -> dict[str, Any]: ...
    def delete_action_async(self, id: str, force: bool = False) -> Any: ...
    def get_triggers(self) -> dict[str, Any]: ...
    def get_execution_async(self, id: str) -> dict[str, Any]: ...
    def get_action_versions_async(self, id: str, page: int | None = None, per_page: int | None = None) -> dict[str, Any]: ...
    def get_trigger_bindings_async(self, id: str, page: int | None = None, per_page: int | None = None) -> dict[str, Any]: ...
    def get_action_version_async(self, action_id: str, version_id: str) -> dict[str, Any]: ...
    def deploy_action_async(self, id: str) -> dict[str, Any]: ...
    def rollback_action_version_async(self, action_id: str, version_id: str) -> dict[str, Any]: ...
    def update_trigger_bindings_async(self, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
