from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class AttackProtection:
    def get_breached_password_detection(self) -> dict[str, Any]: ...
    def update_breached_password_detection_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_brute_force_protection(self) -> dict[str, Any]: ...
    def update_brute_force_protection_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_suspicious_ip_throttling(self) -> dict[str, Any]: ...
    def update_suspicious_ip_throttling_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
