from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class Branding:
    def get(self) -> dict[str, Any]: ...
    def update_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_template_universal_login(self) -> dict[str, Any]: ...
    def delete_template_universal_login(self) -> Any: ...
    def update_template_universal_login_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_default_branding_theme(self) -> dict[str, Any]: ...
    def get_branding_theme_async(self, theme_id: str) -> dict[str, Any]: ...
    def delete_branding_theme_async(self, theme_id: str) -> Any: ...
    def update_branding_theme_async(self, theme_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def create_branding_theme_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
