from typing import Any


class Branding:
    def get_async(self: Any) -> dict[str, Any]: ...
    def update_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_template_universal_login_async(self: Any) -> dict[str, Any]: ...
    def delete_template_universal_login_async(self: Any) -> Any: ...
    def update_template_universal_login_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_default_branding_theme_async(self: Any) -> dict[str, Any]: ...
    def get_branding_theme_async(self: Any, theme_id: str) -> dict[str, Any]: ...
    def delete_branding_theme_async(self: Any, theme_id: str) -> Any: ...
    def update_branding_theme_async(self: Any, theme_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def create_branding_theme_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
