from typing import Any


class Clients:
    def all_async(self: Any, fields: list[str] | None = None, include_fields: bool = True, page: int | None = None, per_page: int | None = None, extra_params: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_async(self: Any, id: str, fields: list[str] | None = None, include_fields: bool = True) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> Any: ...
    def update_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def rotate_secret_async(self: Any, id: str) -> dict[str, Any]: ...
