from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class ClientCredentials:
    def all_async(self, client_id: str) -> list[dict[str, Any]]: ...
    def get_async(self, client_id: str, id: str) -> dict[str, Any]: ...
    def create_async(self, client_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_async(self, client_id: str, id: str) -> dict[str, Any]: ...
