from typing import Any


class ClientCredentials:
    def all_async(self: Any, client_id: str) -> list[dict[str, Any]]: ...
    def get_async(self: Any, client_id: str, id: str) -> dict[str, Any]: ...
    def create_async(self: Any, client_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_async(self: Any, client_id: str, id: str) -> dict[str, Any]: ...
