from typing import Any


class ClientGrants:
    def all_async(self: Any, audience: str | None = None, page: int | None = None, per_page: int | None = None, include_totals: bool = False, client_id: str | None = None, allow_any_organization: bool | None = None) -> Any: ...
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> Any: ...
    def update_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_organizations_async(self: Any, id: str, page: int | None = None, per_page: int | None = None, include_totals: bool = False, from_param: str | None = None, take: int | None = None) -> Any: ...
