from typing import Any


class CustomDomains:
    def all_async(self: Any) -> list[dict[str, Any]]: ...
    def get_async(self: Any, id: str) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> Any: ...
    def create_new_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def verify_async(self: Any, id: str) -> dict[str, Any]: ...
