from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class DeviceCredentials:
    def get_async(self, user_id: str, client_id: str, type: str, fields: list[str] | None = None, include_fields: bool = True, page: int | None = None, per_page: int | None = None, include_totals: bool = False): ...
    def create_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_async(self, id: str) -> Any: ...
