from typing import Any


class DeviceCredentials:
    def get_async(self: Any, user_id: str, client_id: str, type: str, fields: list[str] | None = None, include_fields: bool = True, page: int | None = None, per_page: int | None = None, include_totals: bool = False) -> Any: ...
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> Any: ...
