from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class EmailTemplates:
    def create_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_async(self, template_name: str) -> dict[str, Any]: ...
    def update_async(self, template_name: str, body: dict[str, Any]) -> dict[str, Any]: ...
