from typing import Any


class Emails:
    def get_async(self: Any, fields: list[str] | None = None, include_fields: bool = True) -> dict[str, Any]: ...
    def config_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_async(self: Any) -> Any: ...
    def update_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
