from typing import Any


class EmailTemplates:
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_async(self: Any, template_name: str) -> dict[str, Any]: ...
    def update_async(self: Any, template_name: str, body: dict[str, Any]) -> dict[str, Any]: ...
