from typing import Any


class Guardian:
    def all_factors_async(self: Any) -> list[dict[str, Any]]: ...
    def update_factor_async(self: Any, name: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def update_templates_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_templates_async(self: Any) -> dict[str, Any]: ...
    def get_enrollment_async(self: Any, id: str) -> dict[str, Any]: ...
    def delete_enrollment_async(self: Any, id: str) -> Any: ...
    def create_enrollment_ticket_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_factor_providers_async(self: Any, factor_name: str, name: str) -> dict[str, Any]: ...
    def update_factor_providers_async(self: Any, factor_name: str, name: str, body: dict[str, Any]) -> dict[str, Any]: ...
