from typing import Any


class LogStreams:
    def list_async(self: Any) -> list[dict[str, Any]]: ...
    def get_async(self: Any, id: str) -> dict[str, Any]: ...
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> dict[str, Any]: ...
    def update_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
