from typing import Any


class Organizations:
    def all_organizations_async(self: Any, page: int | None = None, per_page: int | None = None, include_totals: bool = True, from_param: str | None = None, take: int | None = None) -> Any: ...
    def get_organization_by_name_async(self: Any, name: str | None = None) -> dict[str, Any]: ...
    def get_organization_async(self: Any, id: str) -> dict[str, Any]: ...
    def create_organization_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def update_organization_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_organization_async(self: Any, id: str) -> Any: ...
    def all_organization_connections_async(self: Any, id: str, page: int | None = None, per_page: int | None = None) -> list[dict[str, Any]]: ...
    def get_organization_connection_async(self: Any, id: str, connection_id: str) -> dict[str, Any]: ...
    def create_organization_connection_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def update_organization_connection_async(self: Any, id: str, connection_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_organization_connection_async(self: Any, id: str, connection_id: str) -> Any: ...
    def all_organization_members_async(self: Any, id: str, page: int | None = None, per_page: int | None = None, include_totals: bool = True, from_param: str | None = None, take: int | None = None, fields: list[str] | None = None, include_fields: bool = True) -> Any: ...
    def create_organization_members_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_organization_members_async(self: Any, id: str, body: dict[str, Any]) -> Any: ...
    def all_organization_member_roles_async(self: Any, id: str, user_id: str, page: int | None = None, per_page: int | None = None, include_totals: bool = False) -> list[dict[str, Any]]: ...
    def create_organization_member_roles_async(self: Any, id: str, user_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_organization_member_roles_async(self: Any, id: str, user_id: str, body: dict[str, Any]) -> Any: ...
    def all_organization_invitations_async(self: Any, id: str, page: int | None = None, per_page: int | None = None, include_totals: bool = False) -> Any: ...
    def get_organization_invitation_async(self: Any, id: str, invitaton_id: str) -> dict[str, Any]: ...
    def create_organization_invitation_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_organization_invitation_async(self: Any, id: str, invitation_id: str) -> Any: ...
    def get_client_grants_async(self: Any, id: str, audience: str | None = None, client_id: str | None = None, page: int | None = None, per_page: int | None = None, include_totals: bool = False) -> Any: ...
    def add_client_grant_async(self: Any, id: str, grant_id: str) -> dict[str, Any]: ...
    def delete_client_grant_async(self: Any, id: str, grant_id: str) -> dict[str, Any]: ...
