from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class Prompts:
    def get(self) -> dict[str, Any]: ...
    def update_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_custom_text_async(self, prompt: str, language: str): ...
    def update_custom_text_async(self, prompt: str, language: str, body: dict[str, Any]) -> dict[str, Any]: ...
