from typing import Any


class Prompts:
    def get_async(self: Any) -> dict[str, Any]: ...
    def update_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_custom_text_async(self: Any, prompt: str, language: str) -> Any: ...
    def update_custom_text_async(self: Any, prompt: str, language: str, body: dict[str, Any]) -> dict[str, Any]: ...
