from typing import Any


class ResourceServers:
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_all_async(self: Any, page: int | None = None, per_page: int | None = None, include_totals: bool = False) -> Any: ...
    def get_async(self: Any, id: str) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> Any: ...
    def update_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
