from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class ResourceServers:
    def create_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_all_async(self, page: int | None = None, per_page: int | None = None, include_totals: bool = False): ...
    def get_async(self, id: str) -> dict[str, Any]: ...
    def delete_async(self, id: str) -> Any: ...
    def update_async(self, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
