from typing import Any


class Roles:
    def list_async(self: Any, page: int = 0, per_page: int = 25, include_totals: bool = True, name_filter: str | None = None) -> Any: ...
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_async(self: Any, id: str) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> Any: ...
    def update_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def list_users_async(self: Any, id: str, page: int = 0, per_page: int = 25, include_totals: bool = True, from_param: str | None = None, take: int | None = None) -> Any: ...
    def add_users_async(self: Any, id: str, users: List[str]) -> dict[str, Any]: ...
    def list_permissions_async(self: Any, id: str, page: int = 0, per_page: int = 25, include_totals: bool = True) -> Any: ...
    def remove_permissions_async(self: Any, id: str, permissions: List[dict[str, str]]) -> Any: ...
    def add_permissions_async(self: Any, id: str, permissions: List[dict[str, str]]) -> dict[str, Any]: ...
