from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class RulesConfigs:
    def all(self) -> list[dict[str, Any]]: ...
    def unset_async(self, key: str) -> Any: ...
    def set_async(self, key: str, value: str) -> dict[str, Any]: ...
