from typing import Any


class RulesConfigs:
    def all_async(self: Any) -> list[dict[str, Any]]: ...
    def unset_async(self: Any, key: str) -> Any: ...
    def set_async(self: Any, key: str, value: str) -> dict[str, Any]: ...
