from typing import Any


class Rules:
    def all_async(self: Any, stage: str = 'login_success', enabled: bool = True, fields: list[str] | None = None, include_fields: bool = True, page: int | None = None, per_page: int | None = None, include_totals: bool = False) -> Any: ...
    def create_async(self: Any, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_async(self: Any, id: str, fields: list[str] | None = None, include_fields: bool = True) -> dict[str, Any]: ...
    def delete_async(self: Any, id: str) -> Any: ...
    def update_async(self: Any, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
