from typing import Any


class UserBlocks:
    def get_by_identifier_async(self: Any, identifier: str) -> dict[str, Any]: ...
    def unblock_by_identifier_async(self: Any, identifier: dict[str, Any]) -> Any: ...
    def get_async(self: Any, id: str) -> dict[str, Any]: ...
    def unblock_async(self: Any, id: str) -> Any: ...
