from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType
from typing import Any

class Users:
    def list_async(self, page: int = 0, per_page: int = 25, sort: str | None = None, connection: str | None = None, q: str | None = None, search_engine: str | None = None, include_totals: bool = True, fields: list[str] | None = None, include_fields: bool = True): ...
    def create_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_async_async(self, id: str, fields: list[str] | None = None, include_fields: bool = True) -> dict[str, Any]: ...
    def delete_async(self, id: str) -> Any: ...
    def update_async(self, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def list_organizations_async(self, id: str, page: int = 0, per_page: int = 25, include_totals: bool = True): ...
    def list_roles_async(self, id: str, page: int = 0, per_page: int = 25, include_totals: bool = True): ...
    def remove_roles_async(self, id: str, roles: list[str]) -> Any: ...
    def add_roles_async(self, id: str, roles: list[str]) -> dict[str, Any]: ...
    def list_permissions_async(self, id: str, page: int = 0, per_page: int = 25, include_totals: bool = True): ...
    def remove_permissions_async(self, id: str, permissions: list[str]) -> Any: ...
    def add_permissions_async(self, id: str, permissions: list[str]) -> dict[str, Any]: ...
    def delete_multifactor_async(self, id: str, provider: str) -> Any: ...
    def delete_authenticators_async(self, id: str) -> Any: ...
    def unlink_user_account_async(self, id: str, provider: str, user_id: str) -> Any: ...
    def link_user_account_async(self, user_id: str, body: dict[str, Any]) -> list[dict[str, Any]]: ...
    def regenerate_recovery_code_async(self, user_id: str) -> dict[str, Any]: ...
    def get_guardian_enrollments_async(self, user_id: str) -> dict[str, Any]: ...
    def get_log_events_async(self, user_id: str, page: int = 0, per_page: int = 50, sort: str | None = None, include_totals: bool = False): ...
    def invalidate_remembered_browsers_async(self, user_id: str) -> dict[str, Any]: ...
    def get_authentication_methods_async(self, user_id: str) -> dict[str, Any]: ...
    def get_authentication_method_by_id_async(self, user_id: str, authentication_method_id: str) -> dict[str, Any]: ...
    def create_authentication_method_async(self, user_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def update_authentication_methods_async(self, user_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def update_authentication_method_by_id_async(self, user_id: str, authentication_method_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def delete_authentication_methods_async(self, user_id: str) -> Any: ...
    def delete_authentication_method_by_id_async(self, user_id: str, authentication_method_id: str) -> Any: ...
