---
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: ggshield
        name: ggshield
        entry: ggshield secret scan pre-commit
        language: system
        stages: [pre-commit]
