# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BrandingThemeFontInputLabels(UniversalBaseModel):
    """
    Input Labels
    """

    bold: bool = pydantic.Field()
    """
    Input Labels bold
    """

    size: float = pydantic.Field()
    """
    Input Labels size
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
