# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cimd_mapped_private_key_jwt_credential import CimdMappedPrivateKeyJwtCredential


class CimdMappedClientAuthenticationMethodsPrivateKeyJwt(UniversalBaseModel):
    """
    Private Key JWT authentication configuration
    """

    credentials: typing.List[CimdMappedPrivateKeyJwtCredential] = pydantic.Field()
    """
    Credentials derived from the JWKS document
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
