# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ClientEncryptionKey(UniversalBaseModel):
    """
    Encryption used for WsFed responses with this client.
    """

    pub: typing.Optional[str] = pydantic.Field(default=None)
    """
    Encryption Public RSA Key.
    """

    cert: typing.Optional[str] = pydantic.Field(default=None)
    """
    Encryption certificate for public key in X.509 (.CER) format.
    """

    subject: typing.Optional[str] = pydantic.Field(default=None)
    """
    Encryption certificate name for this certificate in the format `/CN={domain}`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
