# This file was auto-generated by Fern from our API Definition.

import typing

from .async_approval_notifications_channels_enum import AsyncApprovalNotificationsChannelsEnum

ClientAsyncApprovalNotificationsChannelsApiPatchConfiguration = typing.List[AsyncApprovalNotificationsChannelsEnum]
