# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .connection_options_shopify import ConnectionOptionsShopify
from .connection_response_common import ConnectionResponseCommon


class ConnectionResponseContentShopify(ConnectionResponseCommon):
    """
    Response for connections with strategy=shopify
    """

    strategy: typing.Literal["shopify"] = "shopify"
    options: typing.Optional[ConnectionOptionsShopify] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
