# This file was auto-generated by Fern from our API Definition.

from .connection_client_secret import ConnectionClientSecret

ConnectionClientSecretExact = ConnectionClientSecret
"""
OAuth2.0 client secret for the Exact Online connection, obtained when registering your application in the Exact App Center.
"""
