# This file was auto-generated by Fern from our API Definition.

import typing

ConnectionProfileCrossAppAccessResourceAppStatusValueEnum = typing.Union[
    typing.Literal["enabled", "disabled"], typing.Any
]
