# This file was auto-generated by Fern from our API Definition.

from .connection_client_secret import ConnectionClientSecret

ConnectionClientSecretPaypal = ConnectionClientSecret
"""
OAuth 2.0 client secret issued by PayPal during application registration. Leave empty to use Auth0 Dev Keys.
"""
