# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .connection_options_o_auth_2 import ConnectionOptionsOAuth2
from .connection_purposes import ConnectionPurposes
from .connection_response_common import ConnectionResponseCommon
from .connection_response_content_o_auth_2_strategy import ConnectionResponseContentOAuth2Strategy


class ConnectionResponseContentOAuth2(ConnectionPurposes, ConnectionResponseCommon):
    """
    Response for connections with strategy=oauth2
    """

    strategy: ConnectionResponseContentOAuth2Strategy
    options: typing.Optional[ConnectionOptionsOAuth2] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
