# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .connection_options_line import ConnectionOptionsLine
from .create_connection_common import CreateConnectionCommon
from .create_connection_request_content_line_strategy import CreateConnectionRequestContentLineStrategy


class CreateConnectionRequestContentLine(CreateConnectionCommon):
    """
    Create a connection with strategy=line
    """

    strategy: CreateConnectionRequestContentLineStrategy
    options: typing.Optional[ConnectionOptionsLine] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
