# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flows_vault_connection_app_id_http_enum import FlowsVaultConnectionAppIdHttpEnum
from .flows_vault_connection_http_oauth_client_credentials_setup import (
    FlowsVaultConnectionHttpOauthClientCredentialsSetup,
)


class CreateFlowsVaultConnectionHttpOauthClientCredentials(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Flows Vault Connection name.
    """

    app_id: FlowsVaultConnectionAppIdHttpEnum
    setup: FlowsVaultConnectionHttpOauthClientCredentialsSetup

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
