# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .connection_options_saml import ConnectionOptionsSaml
from .connection_show_as_button import ConnectionShowAsButton
from .create_connection_common import CreateConnectionCommon
from .create_connection_request_content_saml_strategy import CreateConnectionRequestContentSamlStrategy


class CreateConnectionRequestContentSaml(CreateConnectionCommon):
    """
    Create a connection with strategy=samlp
    """

    strategy: CreateConnectionRequestContentSamlStrategy
    options: typing.Optional[ConnectionOptionsSaml] = None
    show_as_button: typing.Optional[ConnectionShowAsButton] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
