# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .connection_options_evernote_sandbox import ConnectionOptionsEvernoteSandbox
from .create_connection_common import CreateConnectionCommon


class CreateConnectionRequestContentEvernoteSandbox(CreateConnectionCommon):
    """
    Create a connection with strategy=evernote-sandbox
    """

    strategy: typing.Literal["evernote-sandbox"] = "evernote-sandbox"
    options: typing.Optional[ConnectionOptionsEvernoteSandbox] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
