# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .connection_options_instagram import ConnectionOptionsInstagram
from .create_connection_common import CreateConnectionCommon
from .create_connection_request_content_instagram_strategy import CreateConnectionRequestContentInstagramStrategy


class CreateConnectionRequestContentInstagram(CreateConnectionCommon):
    """
    Create a connection with strategy=instagram
    """

    strategy: CreateConnectionRequestContentInstagramStrategy
    options: typing.Optional[ConnectionOptionsInstagram] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
