# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .encryption_key_public_wrapping_algorithm import EncryptionKeyPublicWrappingAlgorithm


class CreateEncryptionKeyPublicWrappingResponseContent(UniversalBaseModel):
    public_key: str = pydantic.Field()
    """
    Public wrapping key in PEM format
    """

    algorithm: EncryptionKeyPublicWrappingAlgorithm

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
