# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flows_vault_connectio_setup_stripe_key_pair import FlowsVaultConnectioSetupStripeKeyPair
from .flows_vault_connection_app_id_stripe_enum import FlowsVaultConnectionAppIdStripeEnum


class CreateFlowsVaultConnectionStripeKeyPair(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Flows Vault Connection name.
    """

    app_id: FlowsVaultConnectionAppIdStripeEnum
    setup: FlowsVaultConnectioSetupStripeKeyPair

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
