# This file was auto-generated by Fern from our API Definition.

import typing

EventStreamCloudEventConnectionUpdatedObject0OptionsConnectionSettingsPkceEnum = typing.Union[
    typing.Literal["auto", "S256", "plain", "disabled"], typing.Any
]
