# This file was auto-generated by Fern from our API Definition.

import typing

EventStreamCloudEventUserCreatedObjectIdentitiesItemCustomProviderEnum = typing.Union[
    typing.Literal["custom"], typing.Any
]
