# This file was auto-generated by Fern from our API Definition.

import typing

EventStreamCloudEventConnectionCreatedPreviousObject2OptionsIdpinitiatedClientProtocolEnum = typing.Union[
    typing.Literal["oidc", "samlp", "wsfed"], typing.Any
]
