# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EventStreamCloudEventContextConnection(UniversalBaseModel):
    """
    The Auth0 Connection used for the authentication transaction that generated the event.
    """

    id: str = pydantic.Field()
    """
    The ID of the connection.
    """

    name: str = pydantic.Field()
    """
    The name of the connection.
    """

    strategy: str = pydantic.Field()
    """
    The auth strategy implemented by the connection.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
