# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .event_stream_cloud_event_user_updated_previous_object_identities_item_passwordless_is_social_enum import (
    EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessIsSocialEnum,
)
from .event_stream_cloud_event_user_updated_previous_object_identities_item_passwordless_profile_data import (
    EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessProfileData,
)
from .event_stream_cloud_event_user_updated_previous_object_identities_item_passwordless_provider_enum import (
    EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessProviderEnum,
)
from .event_stream_cloud_event_user_updated_previous_object_identities_item_passwordless_user_id import (
    EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessUserId,
)


class EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordless(UniversalBaseModel):
    """
    The identity object for passwordless identity providers.
    """

    connection: str = pydantic.Field()
    """
    Name of the connection containing this identity.
    """

    user_id: EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessUserId
    profile_data: typing_extensions.Annotated[
        typing.Optional[EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessProfileData],
        FieldMetadata(alias="profileData"),
        pydantic.Field(alias="profileData"),
    ] = None
    provider: EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessProviderEnum
    is_social: typing_extensions.Annotated[
        EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemPasswordlessIsSocialEnum,
        FieldMetadata(alias="isSocial"),
        pydantic.Field(alias="isSocial"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
