# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .event_stream_cloud_event_a0purpose_enum import EventStreamCloudEventA0PurposeEnum
from .event_stream_cloud_event_group_member_deleted_cloud_event_type_enum import (
    EventStreamCloudEventGroupMemberDeletedCloudEventTypeEnum,
)
from .event_stream_cloud_event_group_member_deleted_data import EventStreamCloudEventGroupMemberDeletedData


class EventStreamCloudEventGroupMemberDeletedCloudEvent(UniversalBaseModel):
    """
    Represents an event that occurs when a member is removed from a group.
    """

    specversion: str = pydantic.Field()
    """
    The version of the CloudEvents specification which the event uses.
    """

    type: EventStreamCloudEventGroupMemberDeletedCloudEventTypeEnum
    source: str = pydantic.Field()
    """
    The source of the event. This will take the form 'urn:auth0:<tenant>.<domain>'.
    """

    id: str = pydantic.Field()
    """
    A unique identifier for the event.
    """

    time: dt.datetime = pydantic.Field()
    """
    An ISO-8601 timestamp indicating when the event physically occurred.
    """

    data: EventStreamCloudEventGroupMemberDeletedData
    a0tenant: str = pydantic.Field()
    """
    The auth0 tenant ID to which the event is associated.
    """

    a0stream: str = pydantic.Field()
    """
    The auth0 event stream ID of the stream the event was delivered on.
    """

    a0purpose: typing.Optional[EventStreamCloudEventA0PurposeEnum] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
