# This file was auto-generated by Fern from our API Definition.

import typing

EventStreamCloudEventOrgConnectionUpdatedPreviousObjectOrganizationAccessLevel1Enum = typing.Union[
    typing.Literal["readonly"], typing.Any
]
