# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .event_stream_cloud_event_org_member_role_assigned_previous_object_organization import (
    EventStreamCloudEventOrgMemberRoleAssignedPreviousObjectOrganization,
)
from .event_stream_cloud_event_org_member_role_assigned_previous_object_role import (
    EventStreamCloudEventOrgMemberRoleAssignedPreviousObjectRole,
)
from .event_stream_cloud_event_org_member_role_assigned_previous_object_user import (
    EventStreamCloudEventOrgMemberRoleAssignedPreviousObjectUser,
)


class EventStreamCloudEventOrgMemberRoleAssignedPreviousObject(UniversalBaseModel):
    """
    The event content as it was prior to the change described by this event, when applicable.
    """

    organization: EventStreamCloudEventOrgMemberRoleAssignedPreviousObjectOrganization
    user: EventStreamCloudEventOrgMemberRoleAssignedPreviousObjectUser
    role: EventStreamCloudEventOrgMemberRoleAssignedPreviousObjectRole

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
