# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flow_action_json_serialize_json_action import FlowActionJsonSerializeJsonAction
from .flow_action_json_serialize_json_params import FlowActionJsonSerializeJsonParams
from .flow_action_json_serialize_json_type import FlowActionJsonSerializeJsonType


class FlowActionJsonSerializeJson(UniversalBaseModel):
    id: str
    alias: typing.Optional[str] = None
    type: FlowActionJsonSerializeJsonType
    action: FlowActionJsonSerializeJsonAction
    allow_failure: typing.Optional[bool] = None
    mask_output: typing.Optional[bool] = None
    params: FlowActionJsonSerializeJsonParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
