# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flow_action_email_verify_email_action import FlowActionEmailVerifyEmailAction
from .flow_action_email_verify_email_params import FlowActionEmailVerifyEmailParams
from .flow_action_email_verify_email_type import FlowActionEmailVerifyEmailType


class FlowActionEmailVerifyEmail(UniversalBaseModel):
    id: str
    alias: typing.Optional[str] = None
    type: FlowActionEmailVerifyEmailType
    action: FlowActionEmailVerifyEmailAction
    allow_failure: typing.Optional[bool] = None
    mask_output: typing.Optional[bool] = None
    params: FlowActionEmailVerifyEmailParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
