# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .flows_vault_connection_http_api_key_setup_in_enum import FlowsVaultConnectionHttpApiKeySetupInEnum
from .flows_vault_connection_setup_type_api_key_enum import FlowsVaultConnectionSetupTypeApiKeyEnum


class FlowsVaultConnectionHttpApiKeySetup(UniversalBaseModel):
    type: FlowsVaultConnectionSetupTypeApiKeyEnum
    name: str
    value: str
    in_: typing_extensions.Annotated[
        FlowsVaultConnectionHttpApiKeySetupInEnum, FieldMetadata(alias="in"), pydantic.Field(alias="in")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
