# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flow_action_whatsapp_send_message_params_payload import FlowActionWhatsappSendMessageParamsPayload
from .flow_action_whatsapp_send_message_params_type import FlowActionWhatsappSendMessageParamsType


class FlowActionWhatsappSendMessageParams(UniversalBaseModel):
    connection_id: str
    sender_id: str
    recipient_number: str
    type: FlowActionWhatsappSendMessageParamsType
    payload: FlowActionWhatsappSendMessageParamsPayload

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
