# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flow_action_bigquery_insert_rows_params_data import FlowActionBigqueryInsertRowsParamsData


class FlowActionBigqueryInsertRowsParams(UniversalBaseModel):
    connection_id: str
    dataset_id: str
    table_id: str
    data: typing.Optional[FlowActionBigqueryInsertRowsParamsData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
