# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flow_action_activecampaign_list_contacts_action import FlowActionActivecampaignListContactsAction
from .flow_action_activecampaign_list_contacts_params import FlowActionActivecampaignListContactsParams
from .flow_action_activecampaign_list_contacts_type import FlowActionActivecampaignListContactsType


class FlowActionActivecampaignListContacts(UniversalBaseModel):
    id: str
    alias: typing.Optional[str] = None
    type: FlowActionActivecampaignListContactsType
    action: FlowActionActivecampaignListContactsAction
    allow_failure: typing.Optional[bool] = None
    mask_output: typing.Optional[bool] = None
    params: FlowActionActivecampaignListContactsParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
