# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .form_field_boolean_config_options import FormFieldBooleanConfigOptions


class FormFieldBooleanConfig(UniversalBaseModel):
    default_value: typing.Optional[bool] = None
    options: typing.Optional[FormFieldBooleanConfigOptions] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
