# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .directory_provisioning_mapping_item import DirectoryProvisioningMappingItem


class GetDirectoryProvisioningDefaultMappingResponseContent(UniversalBaseModel):
    mapping: typing.Optional[typing.List[DirectoryProvisioningMappingItem]] = pydantic.Field(default=None)
    """
    The mapping between Auth0 and IDP user attributes
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
