# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .connection_for_list import ConnectionForList


class ListConnectionsCheckpointPaginatedResponseContent(UniversalBaseModel):
    next: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque identifier for use with the <i>from</i> query parameter for the next page of results.
    """

    connections: typing.Optional[typing.List[ConnectionForList]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
