# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_effective_permission_role_source_response_content import UserEffectivePermissionRoleSourceResponseContent


class ListUserEffectivePermissionRoleSourcesResponseContent(UniversalBaseModel):
    roles: typing.List[UserEffectivePermissionRoleSourceResponseContent] = pydantic.Field()
    """
    Roles with the specified permission assigned to the user, both directly and via groups.
    """

    next: typing.Optional[str] = pydantic.Field(default=None)
    """
    A cursor to be used as the "from" query parameter for the next page of results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
