# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client import Client


class ListClientsOffsetPaginatedResponseContent(UniversalBaseModel):
    start: typing.Optional[float] = None
    limit: typing.Optional[float] = None
    total: typing.Optional[float] = None
    clients: typing.Optional[typing.List[Client]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
