# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .mdl_presentation_request_properties import MdlPresentationRequestProperties


class MdlPresentationRequest(UniversalBaseModel):
    """
    A simplified presentation request
    """

    org_iso_18013_5_1_m_dl: typing_extensions.Annotated[
        MdlPresentationRequestProperties,
        FieldMetadata(alias="org.iso.18013.5.1.mDL"),
        pydantic.Field(alias="org.iso.18013.5.1.mDL"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
