# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OrganizationTemplateUseForOrganizationDiscovery(UniversalBaseModel):
    """
    Controls whether connections from this template are used for organization discovery.
    """

    default_value: bool = pydantic.Field()
    """
    The default value for organization discovery.
    """

    allowed_values: typing.Optional[typing.List[bool]] = pydantic.Field(default=None)
    """
    The allowed values for organization discovery.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
