# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SelfServiceProfileSsoTicketGoogleWorkspaceConfig(UniversalBaseModel):
    """
    Configuration for Google Workspace Directory Sync during the self-service flow.
    """

    sync_users: bool = pydantic.Field()
    """
    Whether to enable Google Workspace Directory Sync for users during the self-service flow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
