# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .session_authentication_signal import SessionAuthenticationSignal


class SessionAuthenticationSignals(UniversalBaseModel):
    """
    Details about authentication signals obtained during the login flow
    """

    methods: typing.Optional[typing.List[SessionAuthenticationSignal]] = pydantic.Field(default=None)
    """
    Contains the authentication methods a user has completed during their session
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
