# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .connection_common import ConnectionCommon
from .connection_options_o_auth_1 import ConnectionOptionsOAuth1


class UpdateConnectionRequestContentOAuth1(ConnectionCommon):
    """
    Update a connection with strategy=oauth1
    """

    options: typing.Optional[ConnectionOptionsOAuth1] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
