# This file was auto-generated by Fern from our API Definition.

import typing

UpdateVariationOverridesMap = typing.Dict[str, typing.Any]
"""
Configuration overrides for this variation; keys must exist in the parent flag parameters. Empty {} is the baseline (control) variation that overrides nothing.
"""
