# This file was auto-generated by Fern from our API Definition.

import typing

from .feature_flag_config_param import FeatureFlagConfigParam

UpdateFeatureFlagParameters = typing.Dict[str, FeatureFlagConfigParam]
"""
Configuration parameters for this feature flag
"""
